# WorldVistA Extended Engineering Console
# Configuration

# Load the standard YottaDB environment
YDB_ENV="/usr/local/etc/ydb_env_set"

# WorldVistA installation
VISTA_HOME="$HOME/wvbuild/VistA-Source"

# Global directory
YDB_GBLDIR="$VISTA_HOME/gld/vista.gld"

# Routine search path
YDB_ROUTINES="$VISTA_HOME/o*($VISTA_HOME/r $HOME/.yottadb/r2.06_x86_64/r $HOME/.yottadb/r) $ydb_dist/libyottadbutil.so"
