WVECWEB ; WorldVistA Web Entry Point
 ;;1.0;WORLDVISTA ENGINEERING CONSOLE;;
ENTRY ;
 N EXP
 S EXP=$ZCMDLINE
 D START(EXP)
 Q

START(EXPLORER) ;

 D INIT^WVECINIT
 I EXPLORER="GLOB" D  Q
 . S ^TMP($J,"WVEC","WEBSTART")=1
 . D START^WVECNAV("WVECGLOB")
 I EXPLORER="RTN" D EN^WVECRTN Q
 I EXPLORER="FM" D START^WVECNAV("WVECFM") Q
 I EXPLORER="KIDS" D EN^WVECKIDS Q
 W !,"Unknown explorer: ",$G(EXPLORER)
 Q
