WVECPROV ; WorldVistA Provider Dispatcher
 ;;4.0;WORLDVISTA ENGINEERING CONSOLE;;

 ;===============================================================
 ; Generic Provider Dispatcher
 ;
 ; Purpose
 ;   Hide all provider-specific knowledge from WVECNAV.
 ;
 ; Navigator calls only WVECPROV.
 ; WVECPROV dispatches to the active provider.
 ;===============================================================
INIT(PROVIDER) ; Initialize Provider

 I PROVIDER="WVECGLOB" D INIT^WVECGLOB Q
 I PROVIDER="WVECRTN" D INIT^WVECRTN Q
 I PROVIDER="WVECKIDS" D INIT^WVECKIDS Q
 I PROVIDER="WVECFM" D INIT^WVECFM Q
 I PROVIDER="WVECM" D INIT^WVECM Q
 I PROVIDER="WVECEXP" D INIT^WVECEXP Q
 D UNKNOWN(PROVIDER)

 Q

BUILD(PROVIDER) ; Build Workspace

 I PROVIDER="WVECGLOB" D LIST^WVECGLOB Q
 I PROVIDER="WVECRTN" D BUILD^WVECRTN Q
 I PROVIDER="WVECKIDS" D BUILD^WVECKIDS Q
 I PROVIDER="WVECFM" D BUILD^WVECFM Q
 I PROVIDER="WVECM" D BUILD^WVECM Q
 I PROVIDER="WVECEXP" D BUILD^WVECEXP Q
 Q
FIND(PROVIDER) ; Find Text

 I PROVIDER="WVECRTN" D FIND^WVECRTN Q
 I PROVIDER="WVECM" D FIND^WVECM Q
 I PROVIDER="WVECFM" D FIND^WVECFM Q
 I PROVIDER="WVECGLOB" D FIND^WVECGLOB Q

 D UNKNOWN(PROVIDER)
 Q

OPEN(PROVIDER,NUMBER) ; Open Selected Item
 S ^TMPXX($J,"PROV","PROVIDER")=PROVIDER
 S ^TMPXX($J,"PROV","NUMBER")=NUMBER
 S ^TMPXX($J,"PROV","BEFORE")=1
 I PROVIDER="WVECGLOB" D  Q
 . S ^TMPXX($J,"PROV","CALL")=1
 . D OPEN^WVECGLOB(NUMBER)
 . S ^TMPXX($J,"PROV","RETURN")=1
 I PROVIDER="WVECRTN" D OPEN^WVECRTN(NUMBER) Q
 I PROVIDER="WVECKIDS" D OPEN^WVECKIDS(NUMBER) Q
 I PROVIDER="WVECFM" D OPEN^WVECFM(NUMBER) Q
 I PROVIDER="WVECM" D OPEN^WVECM(NUMBER) Q
 I PROVIDER="WVECEXP" D OPEN^WVECEXP(NUMBER) Q
 D UNKNOWN(PROVIDER)
 Q


UP(PROVIDER) ; Up One Level

 I PROVIDER="WVECGLOB" D UP^WVECGLOB Q
 I PROVIDER="WVECRTN" D UP^WVECRTN Q
 I PROVIDER="WVECKIDS" D UP^WVECKIDS Q
 I PROVIDER="WVECFM" D UP^WVECFM Q
 I PROVIDER="WVECM" D UP^WVECM Q
 I PROVIDER="WVECEXP" D UP^WVECEXP Q
 D UNKNOWN(PROVIDER)

 Q


TOP(PROVIDER) ; Return To Top

 I PROVIDER="WVECGLOB" D TOP^WVECGLOB Q
 I PROVIDER="WVECRTN" D TOP^WVECRTN Q
 I PROVIDER="WVECKIDS" D TOP^WVECKIDS Q
 I PROVIDER="WVECFM" D TOP^WVECFM Q
 I PROVIDER="WVECM" D TOP^WVECM Q
 I PROVIDER="WVECEXP" D TOP^WVECEXP Q
 D UNKNOWN(PROVIDER)

 Q
GOTO(PROVIDER) ; Go To New Root

 I PROVIDER="WVECGLOB" D GOTO^WVECGLOB Q

 D UNKNOWN(PROVIDER)

 Q

REFRESH(PROVIDER) ; Refresh Workspace

 I PROVIDER="WVECGLOB" D REFRESH^WVECGLOB Q
 I PROVIDER="WVECRTN" D REFRESH^WVECRTN Q
 I PROVIDER="WVECKIDS" D REFRESH^WVECKIDS Q
 I PROVIDER="WVECFM" D REFRESH^WVECFM Q
 I PROVIDER="WVECM" D REFRESH^WVECM Q
 I PROVIDER="WVECEXP" D REFRESH^WVECEXP Q
 D UNKNOWN(PROVIDER)

 Q
HEADER(PROVIDER) ; Display Provider Header

 I PROVIDER="WVECGLOB" D HEADER^WVECGLOB Q
 I PROVIDER="WVECRTN" D HEADER^WVECRTN Q
 I PROVIDER="WVECKIDS" D HEADER^WVECKIDS Q
 I PROVIDER="WVECFM" D HEADER^WVECFM Q
 I PROVIDER="WVECM" D HEADER^WVECM Q
 I PROVIDER="WVECEXP" D HEADER^WVECEXP Q
 D UNKNOWN(PROVIDER)

 Q
INSPECT(PROVIDER) ; Inspect Current Node
 ;
 I PROVIDER="WVECGLOB" D SHOW^WVECNODE Q
 I PROVIDER="WVECRTN" D UNKNOWN(PROVIDER) Q
 I PROVIDER="WVECKIDS" D UNKNOWN(PROVIDER) Q
 I PROVIDER="WVECFM" D UNKNOWN(PROVIDER) Q
 I PROVIDER="WVECEXP" D INSPECT^WVECEXP Q
 D UNKNOWN(PROVIDER)

 Q
UNKNOWN(PROVIDER) ; Unknown Provider

 W !!,"Unknown provider: ",$G(PROVIDER),!

 Q
